# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Darius/Desktop/ECE2140/ece2140/ece2140_cnn_theta/hardware/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.xci
# IP: The module: 'mult_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/ECE2140/ece2140/ece2140_cnn_theta/hardware/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Darius/Desktop/ECE2140/ece2140/ece2140_cnn_theta/hardware/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.xci
# IP: The module: 'mult_gen_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Darius/Desktop/ECE2140/ece2140/ece2140_cnn_theta/hardware/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
