# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.cache/wt [current_project]
set_property parent.project_path /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.dcp
set_property used_in_implementation false [get_files /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_1_1/mult_gen_1.dcp]
read_vhdl -library xil_defaultlib {
  /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/new/fullyconnected.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/bram.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/fifo_parallel.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/fifo.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/convo.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/controller.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/cnn_pkg.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/router.vhd
  /home/wen/Documents/CNN_SoC/src_parallel/cnn_top.vhd
}
read_ip -quiet /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
set_property is_locked true [get_files /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci]

read_ip -quiet /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]
set_property is_locked true [get_files /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/constrs_1/new/clock1.xdc
set_property used_in_implementation false [get_files /home/wen/Documents/CNN_SoC/cnn_parallel/cnn_parallel.srcs/constrs_1/new/clock1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top cnn_top -part xc7k70tfbv676-1


write_checkpoint -force -noxdef cnn_top.dcp

catch { report_utilization -file cnn_top_utilization_synth.rpt -pb cnn_top_utilization_synth.pb }
