# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/clock1.xdc

# IP: ip/c_addsub_0/c_addsub_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_addsub_0 || ORIG_REF_NAME==c_addsub_0}]

# IP: ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]
